[package]
name = "chatlan"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chatlan"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = ["default"] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
if-addrs = "0.13"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
hostname = "0.4"
base64 = "0.22"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
